---
site-title: RonMilton
website: ronmilton.com
website-anchor: <a href="#">RonMilton.com</a>
project-title: Project
description: A technical communication
address: 123 Whereyouat St.
city: Fort Collins
state: CO
zip: 80524
phone: 970-555-1212
toll-free: 800-555-1212
support-email: support@project.org

prose-base: https://prose.io/#RonMilton/project/tree/draft/docs

product-name: Product
current-version: 1.0

company-legal: RonMilton, S.P.
company-name: RonMilton

---
